import os
import time
from datetime import datetime, timedelta, time as dt_time
from dhanhq import DhanContext, HistoricalData, Order
import pandas as pd
import pandas_ta as ta
import sys
import requests


# Retrieve credentials
client_id = os.getenv("client_id")
dhan_pin = os.getenv("dhan_pin")
totp = 0
generate_access_token = f'https://auth.dhan.co/app/generateAccessToken?dhanClientId={client_id}&pin={dhan_pin}&totp={totp}'
response = requests.post(url=generate_access_token)
data = response.json()

access_token = data.get("accessToken") if data else os.getenv("access_token")

# Initialize Dhan Context and Helper Classes
dhan_context = DhanContext(client_id, access_token)
historical_client = HistoricalData(dhan_context)
order_client = Order(dhan_context)

# --- CONFIGURATION ---
SECURITY_ID = "12018" # Example: Suzlon NSE ID
EXCHANGE = "NSE_EQ"
QUANTITY = 1

# Position tracker: 0 = Flat, 1 = Long, -1 = Short
current_position = 0 

print("Starting EMA Crossover Bot...")

while True:
    start_time = dt_time(10,0,0)
    end_time = dt_time(14,45,0)

    if datetime.now().time() <= start_time:
        print("Before market hours\nExiting...")
        sys.exit()

    if datetime.now().time() >= end_time:
        print("After market hours\nExiting...")
        sys.exit()
        
    try:
        # 1. Dynamic Dates (Fetch last 5 days to ensure enough data for EMA calculation)
        now = datetime.now()
        to_date_str = now.strftime("%Y-%m-%d")
        from_date_str = (now - timedelta(days=5)).strftime("%Y-%m-%d")

        # 2. Fetch Data using the historical_client
        historical_data = historical_client.intraday_minute_data(
            security_id=SECURITY_ID,
            exchange_segment=EXCHANGE,
            instrument_type="EQUITY",
            from_date=from_date_str,
            to_date=to_date_str,
            interval=5
        )

        # 3. Parse Data
        # Dhan returns data inside a 'data' key dictionary if successful
        if historical_data.get('status') == 'success' and 'data' in historical_data:
            df = pd.DataFrame(historical_data['data'])
            
            # Use pandas_ta DataFrame extension accessor (.ta) to avoid Pylance import errors
            df["EMA_5"] = df.ta.ema(close="close", length=5)
            df["EMA_10"] = df.ta.ema(close="close", length=10)

            # Drop NA values generated by EMA lookback
            df.dropna(inplace=True)

            if len(df) >= 2:
                # 4. Check conditions using the last two completed candles
                ema5_prev, ema5_curr = df["EMA_5"].iloc[-2], df["EMA_5"].iloc[-1]
                ema10_prev, ema10_curr = df["EMA_10"].iloc[-2], df["EMA_10"].iloc[-1]

                # CROSS UP -> BULLISH (BUY)
                if (ema5_prev < ema10_prev) and (ema5_curr > ema10_curr):
                    print("Bullish Crossover Detected!")
                    
                    if current_position == -1:
                        print("Covering Short Position...")
                        status = order_client.place_order(security_id=SECURITY_ID, exchange_segment=EXCHANGE, transaction_type="BUY", quantity=QUANTITY, order_type="MARKET", product_type="INTRADAY", price=0)
                        print(f"Order Status\n{status}\n")
                    
                    if current_position <= 0:
                        print("Going Long...")
                        status = order_client.place_order(security_id=SECURITY_ID, exchange_segment=EXCHANGE, transaction_type="BUY", quantity=QUANTITY, order_type="MARKET", product_type="INTRADAY", price=0)
                        current_position = 1
                        print(f"Order Status\n{status}\n")

                # CROSS DOWN -> BEARISH (SELL)
                elif (ema5_prev > ema10_prev) and (ema5_curr < ema10_curr):
                    print("Bearish Crossover Detected!")
                    
                    if current_position == 1:
                        print("Covering Long Position...")
                        status = order_client.place_order(security_id=SECURITY_ID, exchange_segment=EXCHANGE, transaction_type="SELL", quantity=QUANTITY, order_type="MARKET", product_type="INTRADAY", price=0)
                        print(f"Order Status\n{status}\n")
                    if current_position >= 0:
                        print("Going Short...")
                        status = order_client.place_order(security_id=SECURITY_ID, exchange_segment=EXCHANGE, transaction_type="SELL", quantity=QUANTITY, order_type="MARKET", product_type="INTRADAY", price=0)
                        current_position = -1
                        print(f"Order Status\n{status}\n")

    except Exception as e:
        print(f"An error occurred during execution: {e}")

    # Sleep for 5 minutes
    time.sleep(5 * 60)