import os
import time
from datetime import datetime, timedelta, time as dt_time
from dhanhq import DhanContext, HistoricalData, Order, Portfolio
import pandas as pd
import pandas_ta as ta
import sys

class Share():
    def __init__(
                self,
                name,
                security_id,
                exchange_segment="NSE",
                quantity=1,
                order_type="MARKET",
                product_type="CNC",
                price=0
                ):
        self.name = name
        self.security_id = security_id
        self.exchange_segment = exchange_segment
        self.quantity = quantity
        self.order_type = order_type
        self.product_type = product_type
        self.price = 0

client_id = os.getenv("client_id")
access_token = os.getenv("access_token")

dhan_context = DhanContext(client_id=client_id,access_token=access_token)
historical_client = HistoricalData(dhan_context)
order_client = Order(dhan_context)

Shares = []

print("Starting EMA Crossover Bot...")

while True:
    start_time = dt_time(10,0,0)
    end_time = dt_time(14,45,0)

    if datetime.now().time() <= start_time:
        print("Before market hours\nExiting...")
        sys.exit()

    if datetime.now().time() >= end_time:
        print("After market hours\nExiting...")


        portfolio = Portfolio(dhan_context=dhan_context)
        positions = portfolio.get_positions()
        
        for position in positions:
            if position["buyQty"] - position["sellQty"] > 0:
                response = order_client.place_order(security_id=position["securityId"], exchange_segment="NSE", transaction_type="SELL", quantity=position["buyQty"]-position["sellQty"], order_type="MARKET", product_type=position["productType"], price=0)
                print(f"tried the final close for {position["tradingSymbol"]}")
                print("Here is the response")
                print(response)
            if position["buyQty"] - position["sellQty"] < 0:
                response = order_client.place_order(security_id=position["securityId"], exchange_segment="NSE", transaction_type="BUY", quantity=position["buyQty"]-position["sellQty"], order_type="MARKET", product_type=position["productType"], price=0)
                print(f"tried the final close for {position["tradingSymbol"]}")
                print("Here is the response")
                print(response)

        sys.exit()
        
    try:
        # 1. Dynamic Dates (Fetch last 5 days to ensure enough data for EMA calculation)
        now = datetime.now()
        to_date_str = now.strftime("%Y-%m-%d")
        from_date_str = (now - timedelta(days=5)).strftime("%Y-%m-%d")

        # 2. Fetch Data using the historical_client
        historical_datas = []
        for share in Shares:
            data = historical_client.intraday_minute_data(
                security_id=share.security_id,
                exchange_segment=share.exchange_segment,
                instrument_type="EQUITY",
                from_date=from_date_str,
                to_date=to_date_str,
                interval=5
            )
            data['name'] = share.name
            data['security_id'] = share.security_id
            data['quantity'] = share.quantity
            historical_datas.append(data)
        # historical_data = historical_client.intraday_minute_data(
        #     security_id=SECURITY_ID,
        #     exchange_segment=EXCHANGE,
        #     instrument_type="EQUITY",
        #     from_date=from_date_str,
        #     to_date=to_date_str,
        #     interval=5
        # )

        # 3. Parse Data
        # Dhan returns data inside a 'data' key dictionary if successful
        df = [pd.DataFrame(historical_data for historical_data in historical_datas)]
        
        # Use pandas_ta DataFrame extension accessor (.ta) to avoid Pylance import errors
        for d in df:
            d["EMA_5"] = d.ta.ema(close="close", length=5)
            d["EMA_10"] = d.ta.ema(close="close", length=10)

        # Drop NA values generated by EMA lookback
            d.dropna(inplace=True)

            if len(d) >= 2:
                # 4. Check conditions using the last two completed candles
                ema5_prev, ema5_curr = d["EMA_5"].iloc[-2], d["EMA_5"].iloc[-1]
                ema10_prev, ema10_curr = d["EMA_10"].iloc[-2], d["EMA_10"].iloc[-1]

                # CROSS UP -> BULLISH (BUY)
                if (ema5_prev < ema10_prev) and (ema5_curr > ema10_curr):
                    print("Bullish Crossover Detected!")
                    print("Going Long...")
                    status = order_client.place_order(security_id=d['security_id'], exchange_segment="NSE", transaction_type="BUY", quantity=d['quantity'], order_type="MARKET", product_type="CNC", price=0)
                    print(f"Order Status\n{status}\n")

                # CROSS DOWN -> BEARISH (SELL)
                elif (ema5_prev > ema10_prev) and (ema5_curr < ema10_curr):
                    print("Bearish Crossover Detected!")
                    print("Going Short...")
                    status = order_client.place_order(security_id=d['security_id'], exchange_segment="NSE", transaction_type="SELL", quantity=d['quantity'], order_type="MARKET", product_type="CNC", price=0)
                    print(f"Order Status\n{status}\n")

    except Exception as e:
        print(f"An error occurred during execution: {e}")

    # Sleep for 5 minutes
    time.sleep(5 * 60)